import React from 'react';
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  ArrowLeft, 
  Download, 
  CreditCard, 
  CheckCircle, 
  AlertCircle,
  BarChart3,
  TrendingUp,
  Target,
  Leaf,
  FileText,
  Star
} from "lucide-react";

interface ReportViewerProps {
  assessmentId: string;
  score: number;
  title: string;
  completedAt: string;
  onBack: () => void;
}

const ReportViewer: React.FC<ReportViewerProps> = ({ 
  assessmentId, 
  score, 
  title, 
  completedAt, 
  onBack 
}) => {
  const getScoreColor = (score: number) => {
    if (score >= 80) return 'text-green-600';
    if (score >= 60) return 'text-yellow-600';
    return 'text-red-600';
  };

  const getScoreLabel = (score: number) => {
    if (score >= 80) return 'Excellent';
    if (score >= 60) return 'Good';
    if (score >= 40) return 'Fair';
    return 'Needs Improvement';
  };

  const getRecommendations = (score: number) => {
    if (score >= 80) {
      return [
        'Maintain your excellent GHG management practices',
        'Consider pursuing third-party verification',
        'Explore advanced carbon reduction strategies',
        'Share best practices with industry peers'
      ];
    } else if (score >= 60) {
      return [
        'Strengthen data collection and monitoring systems',
        'Develop comprehensive Scope 3 emissions inventory',
        'Implement formal GHG management policies',
        'Consider setting science-based targets'
      ];
    } else if (score >= 40) {
      return [
        'Establish basic GHG inventory and monitoring',
        'Define organizational boundaries clearly',
        'Implement data quality assurance procedures',
        'Develop GHG management training programs'
      ];
    } else {
      return [
        'Start with basic GHG awareness training',
        'Identify key emission sources (Scope 1 & 2)',
        'Establish data collection procedures',
        'Consider hiring GHG management expertise'
      ];
    }
  };

  const handleDownloadPaid = () => {
    // Implement payment flow
    alert('Payment integration would be implemented here. This would redirect to a payment processor.');
  };

  const handleDownloadFree = () => {
    // Generate basic PDF report
    const reportContent = `
GHG Readiness Assessment Report
${title}
Completed: ${new Date(completedAt).toLocaleDateString()}

Overall Score: ${score}% - ${getScoreLabel(score)}

This is a basic report. For detailed recommendations and improvement plans, 
please purchase the comprehensive report.

Generated by Aurex Launchpad - GHG Assessment Platform
    `;
    
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ghg-assessment-${assessmentId}-basic.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <Button variant="ghost" onClick={onBack}>
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Dashboard
            </Button>
            <h1 className="text-xl font-semibold">Assessment Report</h1>
            <div className="w-32"></div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto space-y-6">
          {/* Score Overview */}
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle className="text-2xl">{title}</CardTitle>
                  <CardDescription>
                    Completed on {new Date(completedAt).toLocaleDateString()}
                  </CardDescription>
                </div>
                <div className="text-right">
                  <div className={`text-4xl font-bold ${getScoreColor(score)}`}>
                    {score}%
                  </div>
                  <Badge className={`${getScoreColor(score)} bg-opacity-10`}>
                    {getScoreLabel(score)}
                  </Badge>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="text-center">
                  <BarChart3 className="h-8 w-8 mx-auto mb-2 text-blue-600" />
                  <div className="text-sm text-gray-600">Assessment Type</div>
                  <div className="font-medium">ISO 14064 Readiness</div>
                </div>
                <div className="text-center">
                  <Target className="h-8 w-8 mx-auto mb-2 text-green-600" />
                  <div className="text-sm text-gray-600">Categories Evaluated</div>
                  <div className="font-medium">13 Key Areas</div>
                </div>
                <div className="text-center">
                  <TrendingUp className="h-8 w-8 mx-auto mb-2 text-purple-600" />
                  <div className="text-sm text-gray-600">Readiness Level</div>
                  <div className="font-medium">{getScoreLabel(score)}</div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Key Findings */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5" />
                Key Findings
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="flex items-start gap-3">
                  {score >= 60 ? (
                    <CheckCircle className="h-5 w-5 text-green-500 mt-0.5" />
                  ) : (
                    <AlertCircle className="h-5 w-5 text-yellow-500 mt-0.5" />
                  )}
                  <div>
                    <div className="font-medium">Overall GHG Management Readiness</div>
                    <div className="text-sm text-gray-600">
                      Your organization shows {score >= 60 ? 'good' : 'developing'} readiness for 
                      implementing ISO 14064 compliant GHG management systems.
                    </div>
                  </div>
                </div>
                
                <div className="flex items-start gap-3">
                  <Star className="h-5 w-5 text-blue-500 mt-0.5" />
                  <div>
                    <div className="font-medium">Strengths Identified</div>
                    <div className="text-sm text-gray-600">
                      {score >= 80 ? 'Excellent foundation with strong policies and procedures' :
                       score >= 60 ? 'Good understanding of basic GHG management principles' :
                       score >= 40 ? 'Some awareness of GHG management requirements' :
                       'Opportunity to build foundational GHG management capabilities'}
                    </div>
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <TrendingUp className="h-5 w-5 text-purple-500 mt-0.5" />
                  <div>
                    <div className="font-medium">Improvement Opportunities</div>
                    <div className="text-sm text-gray-600">
                      Focus on {score >= 60 ? 'advanced verification and reporting' : 
                                score >= 40 ? 'systematic data collection and monitoring' :
                                'basic GHG inventory development and training'}
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Recommendations Preview */}
          <Card>
            <CardHeader>
              <CardTitle>Recommendations (Preview)</CardTitle>
              <CardDescription>
                Basic recommendations based on your assessment results
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {getRecommendations(score).slice(0, 2).map((rec, index) => (
                  <div key={index} className="flex items-start gap-3">
                    <div className="w-6 h-6 bg-green-100 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5">
                      <span className="text-xs font-medium text-green-600">{index + 1}</span>
                    </div>
                    <div className="text-sm text-gray-700">{rec}</div>
                  </div>
                ))}
                <div className="mt-4 p-4 bg-blue-50 rounded-lg border border-blue-200">
                  <div className="flex items-center gap-2 text-blue-700 font-medium mb-2">
                    <CreditCard className="h-4 w-4" />
                    Get Complete Recommendations
                  </div>
                  <div className="text-sm text-blue-600">
                    Unlock detailed improvement plans, implementation timelines, and expert guidance 
                    with our comprehensive report package.
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Download Options */}
          <Card>
            <CardHeader>
              <CardTitle>Download Report</CardTitle>
              <CardDescription>
                Choose your preferred report format
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="border rounded-lg p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <Leaf className="h-5 w-5 text-green-600" />
                    <span className="font-medium">Basic Report</span>
                    <Badge variant="secondary">Free</Badge>
                  </div>
                  <div className="text-sm text-gray-600 mb-4">
                    • Assessment score and category breakdown
                    • Basic findings summary
                    • General recommendations overview
                  </div>
                  <Button onClick={handleDownloadFree} variant="outline" className="w-full">
                    <Download className="h-4 w-4 mr-2" />
                    Download Free Report
                  </Button>
                </div>

                <div className="border rounded-lg p-4 bg-gradient-to-br from-blue-50 to-purple-50">
                  <div className="flex items-center gap-2 mb-2">
                    <Star className="h-5 w-5 text-blue-600" />
                    <span className="font-medium">Comprehensive Report</span>
                    <Badge className="bg-blue-600">$29</Badge>
                  </div>
                  <div className="text-sm text-gray-600 mb-4">
                    • Detailed analysis and scoring breakdown
                    • Specific improvement recommendations
                    • Implementation timeline and roadmap
                    • Expert consultation session included
                  </div>
                  <Button onClick={handleDownloadPaid} className="w-full bg-blue-600 hover:bg-blue-700">
                    <CreditCard className="h-4 w-4 mr-2" />
                    Purchase Detailed Report
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default ReportViewer;
