-- =====================================================
-- Flyway Migration V1: Create Transactions Table
-- =====================================================
-- Description: Creates the transactions table for storing all blockchain transaction data
-- Author: J4C Database Agent
-- Version: 12.0.0
-- Date: December 2025
-- =====================================================

-- Create transactions table
CREATE TABLE transactions (
    -- Primary key (auto-generated by Panache)
    id BIGSERIAL PRIMARY KEY,

    -- Transaction identifiers
    transactionId VARCHAR(66) NOT NULL UNIQUE,
    hash VARCHAR(66) NOT NULL UNIQUE,

    -- Transaction addresses
    fromAddress VARCHAR(66) NOT NULL,
    toAddress VARCHAR(66) NOT NULL,

    -- Transaction amount (high precision for crypto amounts)
    amount NUMERIC(38, 18) NOT NULL,

    -- Transaction status: PENDING, CONFIRMED, FAILED
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    -- Digital signature (quantum-resistant CRYSTALS-Dilithium)
    signature VARCHAR(4096) NOT NULL,

    -- Block information (null for pending transactions)
    blockHash VARCHAR(66),
    blockNumber BIGINT,

    -- Timestamps
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmedAt TIMESTAMP,

    -- Additional metadata
    metadata TEXT,

    -- Gas information
    gasPrice NUMERIC(18, 9),
    gasLimit BIGINT,
    gasUsed BIGINT,

    -- Transaction details
    nonce BIGINT,
    data TEXT,

    -- Error handling
    errorMessage TEXT,

    -- Constraints
    CONSTRAINT chk_status CHECK (status IN ('PENDING', 'CONFIRMED', 'FAILED')),
    CONSTRAINT chk_amount_positive CHECK (amount >= 0),
    CONSTRAINT chk_gas_positive CHECK (gasPrice IS NULL OR gasPrice >= 0),
    CONSTRAINT chk_block_consistency CHECK (
        (status = 'CONFIRMED' AND blockHash IS NOT NULL AND blockNumber IS NOT NULL AND confirmedAt IS NOT NULL)
        OR
        (status != 'CONFIRMED')
    )
);

-- =====================================================
-- Performance Indexes
-- =====================================================

-- Index on transaction hash (most common lookup)
CREATE UNIQUE INDEX idx_transaction_hash ON transactions(hash);

-- Index on transaction ID
CREATE UNIQUE INDEX idx_transaction_id ON transactions(transactionId);

-- Index on sender address (for address history queries)
CREATE INDEX idx_transaction_from ON transactions(fromAddress);

-- Index on recipient address (for address history queries)
CREATE INDEX idx_transaction_to ON transactions(toAddress);

-- Composite index for address lookups (sender or recipient)
CREATE INDEX idx_transaction_addresses ON transactions(fromAddress, toAddress);

-- Index on status (for pending/confirmed queries)
CREATE INDEX idx_transaction_status ON transactions(status);

-- Composite index for pending transactions sorted by gas price (mempool queries)
CREATE INDEX idx_transaction_pending_gas ON transactions(status, gasPrice DESC, createdAt DESC)
    WHERE status = 'PENDING';

-- Index on block number (for block queries)
CREATE INDEX idx_transaction_block_number ON transactions(blockNumber);

-- Index on block hash (for block queries)
CREATE INDEX idx_transaction_block_hash ON transactions(blockHash);

-- Index on creation timestamp (for time-based queries)
CREATE INDEX idx_transaction_created ON transactions(createdAt DESC);

-- Index on confirmation timestamp (for confirmed transaction queries)
CREATE INDEX idx_transaction_confirmed ON transactions(confirmedAt DESC)
    WHERE confirmedAt IS NOT NULL;

-- Composite index for address + status queries
CREATE INDEX idx_transaction_address_status ON transactions(fromAddress, status);

-- Composite index for nonce ordering within blocks
CREATE INDEX idx_transaction_block_nonce ON transactions(blockNumber, nonce)
    WHERE blockNumber IS NOT NULL;

-- =====================================================
-- Comments for Documentation
-- =====================================================

COMMENT ON TABLE transactions IS 'Stores all blockchain transaction data for Aurigraph V12';
COMMENT ON COLUMN transactions.id IS 'Auto-generated primary key';
COMMENT ON COLUMN transactions.transactionId IS 'Unique transaction identifier (UUID)';
COMMENT ON COLUMN transactions.hash IS 'Transaction hash (SHA-256 or xxHash)';
COMMENT ON COLUMN transactions.fromAddress IS 'Sender wallet address';
COMMENT ON COLUMN transactions.toAddress IS 'Recipient wallet address';
COMMENT ON COLUMN transactions.amount IS 'Transaction amount with 18 decimal precision';
COMMENT ON COLUMN transactions.status IS 'Transaction status: PENDING, CONFIRMED, or FAILED';
COMMENT ON COLUMN transactions.signature IS 'Quantum-resistant digital signature (CRYSTALS-Dilithium)';
COMMENT ON COLUMN transactions.blockHash IS 'Hash of the block containing this transaction (null if pending)';
COMMENT ON COLUMN transactions.blockNumber IS 'Number of the block containing this transaction (null if pending)';
COMMENT ON COLUMN transactions.createdAt IS 'Timestamp when transaction was submitted';
COMMENT ON COLUMN transactions.confirmedAt IS 'Timestamp when transaction was confirmed (null if pending)';
COMMENT ON COLUMN transactions.metadata IS 'Additional transaction metadata as JSON';
COMMENT ON COLUMN transactions.gasPrice IS 'Gas price for transaction prioritization';
COMMENT ON COLUMN transactions.gasLimit IS 'Maximum gas allowed for transaction';
COMMENT ON COLUMN transactions.gasUsed IS 'Actual gas used (null until confirmed)';
COMMENT ON COLUMN transactions.nonce IS 'Transaction nonce for replay protection';
COMMENT ON COLUMN transactions.data IS 'Transaction data payload (smart contract calls, etc.)';
COMMENT ON COLUMN transactions.errorMessage IS 'Error message if transaction failed';

-- =====================================================
-- Performance Statistics Update
-- =====================================================

-- Analyze the table to update PostgreSQL statistics for query optimization
ANALYZE transactions;
