import { EventEmitter } from 'events';
import { ConfigManager } from './ConfigManager';
import { QuantumCryptoManager } from '../crypto/QuantumCryptoManager';
import { ZKProofSystem } from '../zk/ZKProofSystem';
import { AIOptimizer } from '../ai/AIOptimizer';
import { CrossChainBridge } from '../crosschain/CrossChainBridge';
import { ChannelManager } from '../network/ChannelManager';
import { VizorMonitoringService } from '../monitoring/VizorDashboard';
export interface AV18NodeConfig {
    nodeId: string;
    version: string;
    networkType: 'mainnet' | 'testnet' | 'dev';
    maxTPS: number;
    maxLatency: number;
    quantumLevel: number;
    autonomousMode: boolean;
    complianceMode: boolean;
}
export interface NodeMetrics {
    tps: number;
    latency: number;
    quantumOps: number;
    zkProofs: number;
    crossChainTxs: number;
    autonomousOptimizations: number;
    complianceChecks: number;
    uptime: number;
}
export declare class AV18Node extends EventEmitter {
    private logger;
    private config;
    private configManager;
    private consensus;
    private quantumCrypto;
    private zkProofSystem;
    private aiOptimizer;
    private crossChainBridge;
    private channelManager;
    private monitoring;
    private autonomousEngine;
    private complianceEngine;
    private quantumNativeFeatures;
    private ultraHighThroughputProcessor;
    private metrics;
    private startTime;
    private isRunning;
    constructor(configManager: ConfigManager, quantumCrypto: QuantumCryptoManager, zkProofSystem: ZKProofSystem, aiOptimizer: AIOptimizer, crossChainBridge: CrossChainBridge, channelManager: ChannelManager, monitoring: VizorMonitoringService);
    initialize(): Promise<void>;
    private initializeCoreSystem;
    private initializeEnhancements;
    private initializeUltraHighThroughput;
    private initializeAutonomousEngine;
    private initializeComplianceEngine;
    private startThroughputOptimization;
    private optimizeThroughput;
    private updateThroughputMetrics;
    private startAutonomousOperations;
    private performSelfHealing;
    private performHealthCheck;
    private healIssue;
    private performAdaptiveScaling;
    private calculateSystemLoad;
    private scaleUp;
    private scaleDown;
    private performPredictiveMaintenance;
    private performScheduledMaintenance;
    private optimizeMemoryUsage;
    private clearPerformanceCaches;
    private updateOptimizationParameters;
    private startComplianceMonitoring;
    private performComplianceCheck;
    private performRiskAssessment;
    private mitigateRisk;
    private enhanceSecurityMeasures;
    private strengthenComplianceControls;
    private performSanctionScreening;
    private startEnhancedMonitoring;
    private updateMetrics;
    private logEnhancedStatus;
    private emitMetricsUpdate;
    private optimizeNetworkConfiguration;
    private performContinuousOptimization;
    private adaptiveResourceManagement;
    private intelligentLoadBalancing;
    private optimizeShardDistribution;
    private getResourceUtilization;
    private getResourceConstraints;
    private getCPUUsage;
    private getMemoryUsage;
    private getNetworkUsage;
    private getStorageUsage;
    private reallocateResources;
    private getUptime;
    start(): Promise<void>;
    stop(): Promise<void>;
    getStatus(): any;
    getMetrics(): NodeMetrics;
    getEnhancedStatus(): any;
    private calculateComplianceScore;
}
//# sourceMappingURL=AV18Node.d.ts.map