import { Registry } from 'prom-client';
export interface MetricLabels {
    [key: string]: string | number;
}
export declare class PrometheusExporter {
    private logger;
    private registry;
    private server?;
    private tpsGauge;
    private latencyHistogram;
    private activeNodesGauge;
    private blockHeightGauge;
    private transactionCounter;
    private errorCounter;
    private contractExecutionHistogram;
    private contractCreationCounter;
    private contractVerificationGauge;
    private governanceProposalsGauge;
    private tokenizedAssetsGauge;
    private assetTransactionCounter;
    private complianceScoreGauge;
    private quantumOperationsCounter;
    private ntruEncryptionsGauge;
    private zkProofsCounter;
    private quantumSecurityLevelGauge;
    private nodeStatusGauge;
    private peerConnectionsGauge;
    private shardMetricsGauge;
    private resourceUsageGauge;
    private consensusRoundHistogram;
    private leaderElectionCounter;
    private validatorVotesGauge;
    private consensusLatencySummary;
    private bridgeTransactionsCounter;
    private bridgeVolumeGauge;
    private supportedChainsGauge;
    private aiOptimizationsCounter;
    private aiPerformanceGainGauge;
    private aiPredictionsAccuracyGauge;
    constructor();
    private initializeMetrics;
    updateTPS(value: number, network?: string, shard?: string): void;
    recordTransactionLatency(latencyMs: number, type?: string, status?: string): void;
    updateActiveNodes(nodeType: string, count: number): void;
    updateBlockHeight(height: number, chain?: string): void;
    incrementTransactions(type?: string, status?: string): void;
    incrementErrors(component: string, errorType: string): void;
    recordContractExecution(durationMs: number, contractType: string, method: string): void;
    incrementContractsCreated(type: string, template?: string): void;
    updateContractVerification(contractId: string, score: number): void;
    updateGovernanceProposals(status: string, count: number): void;
    updateTokenizedAssets(assetClass: string, jurisdiction: string, count: number): void;
    incrementAssetTransactions(assetClass: string, operation: string): void;
    updateComplianceScore(jurisdiction: string, assetClass: string, score: number): void;
    incrementQuantumOperations(algorithm: string, operation: string): void;
    updateNTRUEncryptions(rate: number): void;
    incrementZKProofs(proofType: string): void;
    updateQuantumSecurityLevel(level: number): void;
    updateNodeStatus(nodeId: string, nodeType: string, status: boolean): void;
    updatePeerConnections(nodeId: string, count: number): void;
    updateShardMetrics(shardId: string, metricType: string, value: number): void;
    updateResourceUsage(nodeId: string, resourceType: string, value: number): void;
    recordConsensusRound(durationMs: number, roundType?: string): void;
    incrementLeaderElections(result: string): void;
    updateValidatorVotes(validatorId: string, votes: number): void;
    recordConsensusLatency(latencyMs: number, phase: string): void;
    incrementBridgeTransactions(sourceChain: string, targetChain: string): void;
    updateBridgeVolume(chain: string, volumeUSD: number): void;
    updateSupportedChains(count: number): void;
    incrementAIOptimizations(optimizationType: string): void;
    updateAIPerformanceGain(metricType: string, gainPercent: number): void;
    updateAIPredictionsAccuracy(predictionType: string, accuracy: number): void;
    start(port?: number): Promise<void>;
    stop(): Promise<void>;
    getRegistry(): Registry;
    getMetricsJSON(): Promise<any>;
}
//# sourceMappingURL=PrometheusExporter.d.ts.map