# Aurigraph DLT SDK — environment configuration
# Generated by @aurigraph/dlt-sdk init on {{GENERATED_AT}}
# DO NOT commit this file to version control (contains secrets).

AURIGRAPH_BASE_URL={{BASE_URL}}
AURIGRAPH_APP_ID={{APP_ID}}
AURIGRAPH_API_KEY={{API_KEY}}
AURIGRAPH_PROJECT_TYPE={{PROJECT_TYPE}}
AURIGRAPH_CALLBACK_URL={{CALLBACK_URL}}
AURIGRAPH_SCOPES={{SCOPES}}
