/**
 * Aurigraph DLT integration — {{APP_NAME}}
 * Generated by @aurigraph/dlt-sdk init on {{GENERATED_AT}}
 * Project type: {{PROJECT_TYPE}}
 */

import { AurigraphClient } from '@aurigraph/dlt-sdk';

// Load env (use your framework's env loader: dotenv, next env, vite env, etc.)
const BASE_URL = process.env.AURIGRAPH_BASE_URL ?? '{{BASE_URL}}';
const API_KEY = process.env.AURIGRAPH_API_KEY ?? '';

export const aurigraph = new AurigraphClient({
  baseUrl: BASE_URL,
  apiKey: API_KEY,
  timeoutMs: 10000,
  maxRetries: 3,
});

/**
 * Example: health check route (Express).
 *
 *   import express from 'express';
 *   import { aurigraph } from './aurigraph-integration';
 *
 *   const app = express();
 *   app.get('/aurigraph/health', async (_req, res) => {
 *     try {
 *       const health = await aurigraph.health.get();
 *       res.json(health);
 *     } catch (err) {
 *       res.status(503).json({ error: (err as Error).message });
 *     }
 *   });
 */

/**
 * Example: submit a signed transaction.
 */
export async function submitTransaction(params: {
  fromAddress: string;
  toAddress: string;
  amount: string;
  asset: string;
  signature: string;
  publicKey: string;
}) {
  return aurigraph.transactions.submit(params);
}

/**
 * Example: list RWAT use cases (9 pre-registered).
 */
export async function listUseCases() {
  return aurigraph.useCases.list();
}
