"""
Aurigraph DLT integration — {{APP_NAME}}
Generated by @aurigraph/dlt-sdk init on {{GENERATED_AT}}
Project type: {{PROJECT_TYPE}}

Requires: httpx (or use requests / urllib3)
  pip install httpx
"""
import os
from typing import Any, Dict

import httpx

BASE_URL: str = os.environ.get("AURIGRAPH_BASE_URL", "{{BASE_URL}}")
API_KEY: str = os.environ.get("AURIGRAPH_API_KEY", "")
APP_ID: str = os.environ.get("AURIGRAPH_APP_ID", "{{APP_ID}}")


def _headers() -> Dict[str, str]:
    return {
        "X-API-Key": API_KEY,
        "X-App-Id": APP_ID,
        "Content-Type": "application/json",
    }


async def get_health() -> Dict[str, Any]:
    async with httpx.AsyncClient(timeout=10.0) as client:
        r = await client.get(f"{BASE_URL}/api/v11/health", headers=_headers())
        r.raise_for_status()
        return r.json()


async def list_use_cases() -> Any:
    async with httpx.AsyncClient(timeout=10.0) as client:
        r = await client.get(f"{BASE_URL}/api/v11/use-cases", headers=_headers())
        r.raise_for_status()
        return r.json()


async def submit_transaction(payload: Dict[str, Any]) -> Dict[str, Any]:
    async with httpx.AsyncClient(timeout=10.0) as client:
        r = await client.post(
            f"{BASE_URL}/api/v11/transactions",
            headers=_headers(),
            json=payload,
        )
        r.raise_for_status()
        return r.json()


# Example FastAPI route:
#
#   from fastapi import FastAPI
#   from aurigraph_integration import get_health
#
#   app = FastAPI()
#
#   @app.get("/aurigraph/health")
#   async def health():
#       return await get_health()
