/**
 * Aurigraph DLT SDK — quickstart example
 * Generated by @aurigraph/dlt-sdk init on {{GENERATED_AT}}
 * Project: {{APP_NAME}} (type: {{PROJECT_TYPE}})
 */

import { AurigraphClient } from '@aurigraph/dlt-sdk';

const client = new AurigraphClient({
  baseUrl: process.env.AURIGRAPH_BASE_URL ?? '{{BASE_URL}}',
  apiKey: process.env.AURIGRAPH_API_KEY ?? '',
});

async function main(): Promise<void> {
  const health = await client.health.get();
  console.log('Aurigraph health:', health.status);

  const stats = await client.stats.get();
  console.log(`TPS: ${stats.tps}, nodes: ${stats.activeNodes}`);

  const useCases = await client.useCases.list();
  console.log(`${useCases.length} RWAT use cases registered`);
}

main().catch((err) => {
  console.error('Aurigraph SDK error:', err);
  process.exit(1);
});
