/**
 * Aurigraph DLT integration — {{APP_NAME}}
 * Generated by @aurigraph/dlt-sdk init on {{GENERATED_AT}}
 * Project type: {{PROJECT_TYPE}}
 *
 * Add this class to your Quarkus project and inject it wherever you need
 * to call the Aurigraph DLT V12 platform.
 *
 * application.properties:
 *   aurigraph.base-url=${AURIGRAPH_BASE_URL:{{BASE_URL}}}
 *   aurigraph.api-key=${AURIGRAPH_API_KEY:}
 *   aurigraph.app-id=${AURIGRAPH_APP_ID:{{APP_ID}}}
 */
package io.aurigraph.integration;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.eclipse.microprofile.config.inject.ConfigProperty;

@ApplicationScoped
public class AurigraphConfig {

    @ConfigProperty(name = "aurigraph.base-url", defaultValue = "{{BASE_URL}}")
    String baseUrl;

    @ConfigProperty(name = "aurigraph.api-key", defaultValue = " ")
    String apiKey;

    @ConfigProperty(name = "aurigraph.app-id", defaultValue = "{{APP_ID}}")
    String appId;

    public String getBaseUrl() {
        return baseUrl;
    }

    public String getApiKey() {
        return apiKey;
    }

    public String getAppId() {
        return appId;
    }

    /**
     * Example: build HTTP headers for Aurigraph V11 API calls.
     */
    public java.util.Map<String, String> headers() {
        return java.util.Map.of(
            "X-API-Key", apiKey,
            "X-App-Id", appId,
            "Content-Type", "application/json"
        );
    }
}
