/**
 * Template renderer — `aurigraph-tokenization.config.ts`
 */

import type { AssetField, Jurisdiction, TokenType, UseCase } from '../tokenize-prompts.js';

export interface ConfigTemplateInput {
  useCase: UseCase;
  tokenType: TokenType;
  dmrvFramework: string;
  jurisdiction: Jurisdiction;
  fields: AssetField[];
  generatedAt: string;
}

/**
 * Render a TypeScript interface for the caller's asset model.
 */
function renderAssetInterface(fields: AssetField[]): string {
  if (fields.length === 0) {
    return '  // No fields captured — add your own here.\n  [k: string]: unknown;';
  }
  return fields
    .map((f) => `  ${f.name}: ${f.type};`)
    .join('\n');
}

export function renderConfig(input: ConfigTemplateInput): string {
  return `// Auto-generated by @aurigraph/dlt-sdk tokenize
// Generated at: ${input.generatedAt}
// Do not edit — re-run the wizard to regenerate.

export const AURIGRAPH_TOKENIZATION = {
  useCase: '${input.useCase}',
  tokenType: '${input.tokenType}',
  dmrvFramework: '${input.dmrvFramework}',
  jurisdiction: '${input.jurisdiction}',
  appId: process.env.AURIGRAPH_APP_ID ?? '',
  apiKey: process.env.AURIGRAPH_API_KEY ?? '',
  baseUrl: process.env.AURIGRAPH_BASE_URL ?? 'https://dlt.aurigraph.io',
} as const;

export type AurigraphUseCase = typeof AURIGRAPH_TOKENIZATION.useCase;
export type AurigraphTokenType = typeof AURIGRAPH_TOKENIZATION.tokenType;

/**
 * Your app's asset model — captured from the tokenize wizard.
 * Edit freely; only the generated service file reads this shape.
 */
export interface MyAsset {
${renderAssetInterface(input.fields)}
}
`;
}
