/**
 * Template renderer — `aurigraph-tokenization.example.ts`
 */

import type { TokenType, UseCase } from '../tokenize-prompts.js';

export interface ExampleTemplateInput {
  useCase: UseCase;
  tokenType: TokenType;
  generatedAt: string;
}

export function renderExample(input: ExampleTemplateInput): string {
  const compositeBlock =
    input.tokenType === 'COMPOSITE'
      ? `
  // 5. [COMPOSITE only] Assemble the composite bundle
  const { compositeTokenId, bundleHash } = await aurigraph.assembleComposite({
    primaryAssetId: aurigraphAssetId,
    components: [
      { assetId: 'component-device-001', role: 'DEVICE' },
      { assetId: 'component-signature-002', role: 'EDITORIAL' },
    ],
    ownerId: 'newsroom-alpha',
  });
  console.log('composite token:', compositeTokenId, 'bundleHash:', bundleHash);
`
      : `
  const compositeTokenId: string | undefined = undefined;
`;

  const mintAssetId =
    input.tokenType === 'COMPOSITE' ? 'compositeTokenId ?? aurigraphAssetId' : 'aurigraphAssetId';

  return `// Auto-generated by @aurigraph/dlt-sdk tokenize
// Generated at: ${input.generatedAt}
//
// Usage example — demonstrates the full 5-stage pipeline for use case
// ${input.useCase} (${input.tokenType}). Run with:
//   npx tsx aurigraph-tokenization.example.ts

import { AurigraphTokenizationService } from './aurigraph-tokenization.service.js';
import type { MyAsset } from './aurigraph-tokenization.config.js';

async function main(): Promise<void> {
  const aurigraph = new AurigraphTokenizationService();

  // 1. Your app creates an asset (mimic your existing flow)
  const myAsset: MyAsset = {
    assetId: 'demo-asset-' + Date.now(),
    ownerId: 'demo-owner',
    contentHash: 'sha256:' + 'a'.repeat(64),
    createdAt: new Date(),
  } as unknown as MyAsset;

  // 2. STAGE 1 — Register on Aurigraph
  const { aurigraphAssetId } = await aurigraph.registerAsset(myAsset);
  console.log('registered:', aurigraphAssetId);

  // 3. STAGE 2 — Record DMRV events as they happen
  await aurigraph.recordDmrvEvent({
    assetId: aurigraphAssetId,
    eventType: 'BASELINE',
    quantity: 1,
    unit: 'unit',
  });

  // 4. STAGE 3 — Verify (attestation from a trusted party)
  await aurigraph.verifyAsset(aurigraphAssetId, 'attestor-signature-demo');
${compositeBlock}
  // 6. STAGE 4 — Mint the token to the owner wallet
  const { tokenId, txHash } = await aurigraph.mintToken(
    ${mintAssetId},
    1,
    '0xDemoOwnerWallet',
  );
  console.log('minted:', tokenId, 'tx:', txHash);

  // 7. Clean shutdown (stops heartbeat timer)
  aurigraph.dispose();
}

main().catch((err: unknown) => {
  // eslint-disable-next-line no-console
  console.error('tokenization example failed:', err);
  process.exit(1);
});
`;
}
