/**
 * Template renderer — `TOKENIZATION_INTEGRATION.md`
 */

import type {
  Jurisdiction,
  LifecycleHooks,
  TokenType,
  UseCase,
} from '../tokenize-prompts.js';

export interface IntegrationTemplateInput {
  useCase: UseCase;
  tokenType: TokenType;
  dmrvFramework: string;
  jurisdiction: Jurisdiction;
  hooks: LifecycleHooks;
  approvedScopes: string[];
  pendingScopes: string[];
  generatedAt: string;
}

const REQUIRED_SCOPES: Record<string, string[]> = {
  registerAsset: ['registry:write'],
  recordDmrvEvent: ['dmrv:write'],
  verifyAsset: ['dmrv:write'],
  mintToken: ['mint:token'],
  assembleComposite: ['contracts:write', 'registry:write'],
  deriveToken: ['contracts:write'],
};

function renderScopeTable(tokenType: TokenType): string {
  const rows: Array<[string, string]> = [
    ['registerAsset', REQUIRED_SCOPES.registerAsset.join(', ')],
    ['recordDmrvEvent', REQUIRED_SCOPES.recordDmrvEvent.join(', ')],
    ['verifyAsset', REQUIRED_SCOPES.verifyAsset.join(', ')],
    ['mintToken', REQUIRED_SCOPES.mintToken.join(', ')],
  ];
  if (tokenType === 'COMPOSITE') {
    rows.push(['assembleComposite', REQUIRED_SCOPES.assembleComposite.join(', ')]);
  }
  if (tokenType === 'SECONDARY') {
    rows.push(['deriveToken', REQUIRED_SCOPES.deriveToken.join(', ')]);
  }
  const header = '| Method | Required scopes |\n| --- | --- |\n';
  return header + rows.map((r) => `| \`${r[0]}\` | \`${r[1]}\` |`).join('\n');
}

function renderScopeStatus(approved: string[], pending: string[]): string {
  const all = new Set<string>();
  Object.values(REQUIRED_SCOPES).forEach((arr) => arr.forEach((s) => all.add(s)));
  const rows = Array.from(all).map((s) => {
    if (approved.includes(s)) return `- [x] \`${s}\` — approved`;
    if (pending.includes(s)) return `- [ ] \`${s}\` — **pending admin approval**`;
    return `- [ ] \`${s}\` — not requested yet`;
  });
  return rows.join('\n');
}

export function renderIntegration(input: IntegrationTemplateInput): string {
  return `# Aurigraph DLT Tokenization Integration

> Generated by \`@aurigraph/dlt-sdk tokenize\` at ${input.generatedAt}.
> Re-run the wizard to regenerate this file.

## Overview

This integration wires your application into Aurigraph's 5-stage RWAT
tokenization pipeline for use case **${input.useCase}** (${input.tokenType}).

| Stage | Method | When it fires in your app |
| --- | --- | --- |
| 1 — Register | \`registerAsset\` | ${input.hooks.onRegister} |
| 2 — Monitoring | \`recordDmrvEvent\` | ${input.hooks.onMonitoring} |
| 3 — Verification | \`verifyAsset\` | ${input.hooks.onVerification} |
| 4 — Mint / Issue | \`mintToken\` | ${input.hooks.onMint} |${
    input.tokenType === 'COMPOSITE'
      ? `\n| 5 — Assemble | \`assembleComposite\` | ${input.hooks.onAssemble ?? ''} |`
      : ''
  }

## Configuration

The generated \`aurigraph-tokenization.config.ts\` captures:

- **Use case**: \`${input.useCase}\`
- **Token type**: \`${input.tokenType}\`
- **DMRV framework**: \`${input.dmrvFramework}\`
- **Jurisdiction**: \`${input.jurisdiction}\`

Credentials are loaded at runtime from \`.env.aurigraph\`:

\`\`\`
AURIGRAPH_APP_ID=...
AURIGRAPH_API_KEY=...
AURIGRAPH_BASE_URL=https://dlt.aurigraph.io
\`\`\`

## Scope requirements

Each method in the generated service requires one or more scopes on your
SDK app registration:

${renderScopeTable(input.tokenType)}

### Current scope status

${renderScopeStatus(input.approvedScopes, input.pendingScopes)}

## Requesting admin approval for pending scopes

Write scopes (\`registry:write\`, \`dmrv:write\`, \`mint:token\`,
\`contracts:write\`) are admin-gated. Request approval via:

\`\`\`bash
curl -X POST https://dlt.aurigraph.io/api/v11/sdk/scopes/request \\
  -H "Content-Type: application/json" \\
  -H "X-Aurigraph-App-Id: $AURIGRAPH_APP_ID" \\
  -H "X-Aurigraph-Api-Key: $AURIGRAPH_API_KEY" \\
  -d '{"scopes": ["dmrv:write", "mint:token"], "reason": "production tokenization"}'
\`\`\`

A platform admin will review the request and approve/deny in the Aurigraph
Enterprise Portal.

## Error codes

| HTTP | Code | Meaning | Remedy |
| --- | --- | --- | --- |
| 401 | \`AUTH_MISSING\` | appId/apiKey not set | Check \`.env.aurigraph\` |
| 403 | \`SCOPE_DENIED\` | method requires a scope you don't have | Request admin approval |
| 409 | \`IDEMPOTENT_REPLAY\` | duplicate request detected | Inspect response — likely safe to ignore |
| 422 | \`VALIDATION_ERROR\` | bad payload (missing fields, wrong types) | Verify \`MyAsset\` shape matches server schema |
| 429 | \`RATE_LIMITED\` | heartbeat/request throttled | Back off; see \`hello.rateLimit\` |
| 503 | \`REGISTRY_DEGRADED\` | server in read-only mode | Retry with backoff |

All responses follow RFC 7807 (\`application/problem+json\`).

## Next steps

1. **Import the service** in your app:
   \`\`\`ts
   import { AurigraphTokenizationService } from './aurigraph-tokenization.service';
   const aurigraph = new AurigraphTokenizationService();
   \`\`\`
2. **Wire the 5 stages** into your existing lifecycle events.
3. **Run the example**:
   \`\`\`bash
   npx tsx aurigraph-tokenization.example.ts
   \`\`\`
4. **Monitor** the handshake log line — if scopes are missing, the
   write methods will 403 until you request approval.

## References

- Handshake protocol: https://dlt.aurigraph.io/docs/handshake
- DMRV framework index: https://dlt.aurigraph.io/docs/dmrv
- RWAT use-case catalog: https://dlt.aurigraph.io/docs/use-cases
- SDK README: https://github.com/Aurigraph-DLT-Corp/Aurigraph-DLT/tree/V12/aurigraph-sdk/typescript
`;
}
