#!/usr/bin/env bash
# ADM-173 loop-closure scorecard — weekly recursive-improvement health check.
# Usage: ./scripts/adm-loop-scorecard.sh [--write]
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
LOG="$REPO_ROOT/docs/adm/gate-telemetry.jsonl"
OUT="$REPO_ROOT/docs/adm/LOOP_CLOSURE_SCORECARD.md"
WRITE=0
[ "${1:-}" = "--write" ] && WRITE=1

cd "$REPO_ROOT"

# Gate stats (last 30 days if jq unavailable, count all)
gate_total=0 gate_skip=0 gate_bypass=0
if [ -f "$LOG" ]; then
  gate_total=$(wc -l <"$LOG" | tr -d ' ')
  gate_skip=$(rg -c '"verdict":"SKIP"' "$LOG" 2>/dev/null || echo 0)
  gate_bypass=$(rg -c '"verdict":"BYPASS"' "$LOG" 2>/dev/null || echo 0)
fi

adm_commits=$(git log --since='30 days ago' --oneline --grep='docs(adm)' 2>/dev/null | wc -l | tr -d ' ')
ins_tags=$(rg -c 'INS-' aurigraph-dlt.md session.md 2>/dev/null | awk -F: '{s+=$2} END{print s+0}')
iter_tests=$(git log --since='30 days ago' --oneline --grep='AV11-2936 iter-' 2>/dev/null | wc -l | tr -d ' ')

# Loop closure rate (ADM-173 formula):
#   (adm_sync_commits + ins_entries + iter_commits - gate_skips) / max(1, adm_sync + ins + iter + gate_total)
numer=$((adm_commits + ins_tags + iter_tests))
denom=$((numer + gate_skip + gate_bypass))
if [ "$denom" -gt 0 ]; then
  closure_pct=$(( (numer * 100) / denom ))
else
  closure_pct=0
fi

grade="NEEDS WORK"
[ "$closure_pct" -ge 90 ] && grade="9+/10 TARGET"
[ "$closure_pct" -ge 75 ] && [ "$closure_pct" -lt 90 ] && grade="GOOD (7.5–8.5)"
[ "$closure_pct" -ge 60 ] && [ "$closure_pct" -lt 75 ] && grade="FAIR"

report="$(cat <<EOF
# ADM Loop Closure Scorecard

> Auto-generated by \`scripts/adm-loop-scorecard.sh\` · **ADM-173**
> Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)

## Score: **${closure_pct}%** — ${grade}

| Metric (30d window) | Count |
|---------------------|------:|
| \`docs(adm)\` sync commits | ${adm_commits} |
| Coverage iter commits (AV11-2936) | ${iter_tests} |
| INS-* references (session + aurigraph-dlt) | ${ins_tags} |
| Gate telemetry events (all time) | ${gate_total} |
| Gate SKIP events | ${gate_skip} |
| Gate BYPASS events | ${gate_bypass} |

## Target (9+/10)

- **Loop closure ≥ 90%** — incidents → ADM-ID + test + deploy verify
- **Gate SKIP ≤ 2 per sprint** — log every skip via \`./scripts/adm-gate-log.sh\`
- **ADM drift = 0** — \`./scripts/adm-sync.sh --check\` passes before session work
- **KGraph-first** — \`kgraph_health\` at session start (ADM-170)

## Operator commands

\`\`\`bash
./scripts/adm-sync.sh --check          # drift gate
./scripts/adm-sync.sh --sync           # mirror all ADM copies
./scripts/adm-gate-log.sh SCMAgent SKIP "reason"
./scripts/adm-session-start.sh         # kgraph + sync check + scorecard
\`\`\`
EOF
)"

echo "$report"
if [ "$WRITE" -eq 1 ]; then
  printf '%s\n' "$report" >"$OUT"
  echo "📝 Wrote $OUT"
fi
