#!/bin/bash

# Aurigraph DLT SSL/HTTPS Setup Script
# Enables HTTPS on dlt.aurigraph.io

echo "🔒 Aurigraph SSL/HTTPS Setup"
echo "============================"
echo "Domain: dlt.aurigraph.io"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
DOMAIN="dlt.aurigraph.io"
EMAIL="admin@aurigraph.io"
API_PORT=4004
WS_PORT=4005
DASHBOARD_PORT=8050

# Function to print colored output
print_status() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   print_error "This script must be run as root (use sudo)"
   exit 1
fi

# Check system
print_info "Checking system requirements..."

# Update package list
apt-get update -qq

# Install required packages
print_info "Installing required packages..."

# Install nginx if not present
if ! command -v nginx &> /dev/null; then
    print_info "Installing nginx..."
    apt-get install -y nginx
    print_status "Nginx installed"
else
    print_status "Nginx already installed"
fi

# Install certbot if not present
if ! command -v certbot &> /dev/null; then
    print_info "Installing certbot..."
    apt-get install -y certbot python3-certbot-nginx
    print_status "Certbot installed"
else
    print_status "Certbot already installed"
fi

# Check if domain resolves
print_info "Checking domain resolution..."
DOMAIN_IP=$(dig +short $DOMAIN)
SERVER_IP=$(curl -s ifconfig.me)

if [ -z "$DOMAIN_IP" ]; then
    print_error "Domain $DOMAIN does not resolve"
    print_info "Please ensure DNS A record points to $SERVER_IP"
    exit 1
fi

if [ "$DOMAIN_IP" != "$SERVER_IP" ]; then
    print_warning "Domain points to $DOMAIN_IP but server IP is $SERVER_IP"
    read -p "Continue anyway? (y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
else
    print_status "Domain resolves correctly to $SERVER_IP"
fi

# Stop nginx temporarily
print_info "Stopping nginx temporarily..."
systemctl stop nginx

# Create nginx configuration
print_info "Creating nginx configuration..."

cat > /etc/nginx/sites-available/$DOMAIN << 'EOF'
# Aurigraph DLT HTTPS Configuration
# Generated by setup-ssl.sh

upstream aurigraph_api {
    server 127.0.0.1:4004;
    keepalive 64;
}

upstream aurigraph_ws {
    server 127.0.0.1:4005;
    keepalive 64;
}

upstream vizro_dashboard {
    server 127.0.0.1:8050;
    keepalive 32;
}

# HTTP server - redirect to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name dlt.aurigraph.io;
    
    # Allow Let's Encrypt challenges
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }
    
    # Redirect all other traffic to HTTPS
    location / {
        return 301 https://$server_name$request_uri;
    }
}

# HTTPS server
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name dlt.aurigraph.io;
    
    # SSL certificates (will be added by certbot)
    # ssl_certificate /etc/letsencrypt/live/dlt.aurigraph.io/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/dlt.aurigraph.io/privkey.pem;
    
    # SSL configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_stapling on;
    ssl_stapling_verify on;
    
    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    
    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css text/xml text/javascript application/json application/javascript application/xml+rss application/rss+xml application/atom+xml image/svg+xml text/javascript application/vnd.ms-fontobject application/x-font-ttf font/opentype;
    
    # Rate limiting zones
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=100r/s;
    limit_req_zone $binary_remote_addr zone=ws_limit:10m rate=10r/s;
    
    # Logging
    access_log /var/log/nginx/dlt.aurigraph.io.access.log;
    error_log /var/log/nginx/dlt.aurigraph.io.error.log;
    
    # Root location - serve main application
    location / {
        proxy_pass http://aurigraph_api;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_buffering off;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
    
    # API endpoints
    location /channel/ {
        limit_req zone=api_limit burst=100 nodelay;
        proxy_pass http://aurigraph_api;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
        
        # CORS headers
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization' always;
        
        if ($request_method = 'OPTIONS') {
            return 204;
        }
    }
    
    # Health check endpoint
    location /health {
        proxy_pass http://aurigraph_api;
        access_log off;
    }
    
    # API documentation
    location /api/ {
        limit_req zone=api_limit burst=50 nodelay;
        proxy_pass http://aurigraph_api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    
    # WebSocket endpoint
    location /ws {
        limit_req zone=ws_limit burst=5 nodelay;
        proxy_pass http://aurigraph_ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }
    
    # Vizro Dashboard
    location /vizro {
        rewrite ^/vizro(.*)$ $1 break;
        proxy_pass http://vizro_dashboard;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Script-Name /vizro;
        proxy_buffering off;
    }
    
    # Dashboard assets
    location /_dash {
        proxy_pass http://vizro_dashboard;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    
    # Static file caching
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf|eot)$ {
        proxy_pass http://aurigraph_api;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
    
    # Block hidden files
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
    
    # Custom error pages
    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;
    
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }
    
    location = /50x.html {
        root /usr/share/nginx/html;
        internal;
    }
}
EOF

# Create symbolic link
print_info "Enabling site configuration..."
ln -sf /etc/nginx/sites-available/$DOMAIN /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default 2>/dev/null

# Test nginx configuration
print_info "Testing nginx configuration..."
nginx -t
if [ $? -ne 0 ]; then
    print_error "Nginx configuration test failed"
    exit 1
fi
print_status "Nginx configuration valid"

# Start nginx
print_info "Starting nginx..."
systemctl start nginx
systemctl enable nginx
print_status "Nginx started"

# Obtain SSL certificate
print_info "Obtaining SSL certificate from Let's Encrypt..."
echo ""
print_warning "Please ensure that:"
print_warning "1. Domain $DOMAIN points to this server"
print_warning "2. Ports 80 and 443 are open"
print_warning "3. No other service is using these ports"
echo ""

# Run certbot
certbot --nginx -d $DOMAIN --non-interactive --agree-tos --email $EMAIL --redirect

if [ $? -eq 0 ]; then
    print_status "SSL certificate obtained successfully!"
else
    print_error "Failed to obtain SSL certificate"
    print_info "You can try manual setup with: sudo certbot --nginx -d $DOMAIN"
    exit 1
fi

# Reload nginx with SSL
print_info "Reloading nginx with SSL configuration..."
systemctl reload nginx
print_status "Nginx reloaded with SSL"

# Setup auto-renewal
print_info "Setting up automatic certificate renewal..."
cat > /etc/cron.d/certbot-renewal << EOF
# Renew Let's Encrypt certificates twice daily
0 0,12 * * * root certbot renew --quiet --post-hook "systemctl reload nginx"
EOF
print_status "Auto-renewal configured"

# Create monitoring script
print_info "Creating SSL monitoring script..."
cat > /usr/local/bin/check-ssl.sh << 'EOF'
#!/bin/bash
# Check SSL certificate expiry

DOMAIN="dlt.aurigraph.io"
EXPIRY=$(echo | openssl s_client -servername $DOMAIN -connect $DOMAIN:443 2>/dev/null | openssl x509 -noout -dates | grep notAfter | cut -d= -f2)
EXPIRY_EPOCH=$(date -d "$EXPIRY" +%s)
NOW_EPOCH=$(date +%s)
DAYS_LEFT=$(( ($EXPIRY_EPOCH - $NOW_EPOCH) / 86400 ))

echo "SSL Certificate Status for $DOMAIN:"
echo "Expires: $EXPIRY"
echo "Days remaining: $DAYS_LEFT"

if [ $DAYS_LEFT -lt 30 ]; then
    echo "⚠️  WARNING: Certificate expires in less than 30 days!"
elif [ $DAYS_LEFT -lt 7 ]; then
    echo "🚨 CRITICAL: Certificate expires in less than 7 days!"
else
    echo "✅ Certificate is valid"
fi
EOF

chmod +x /usr/local/bin/check-ssl.sh
print_status "SSL monitoring script created"

# Test HTTPS endpoints
print_info "Testing HTTPS endpoints..."
echo ""

# Wait for services to stabilize
sleep 3

# Test health endpoint
HEALTH_CHECK=$(curl -sSL -o /dev/null -w "%{http_code}" https://$DOMAIN/health)
if [ "$HEALTH_CHECK" = "200" ]; then
    print_status "Health endpoint: https://$DOMAIN/health ✓"
else
    print_warning "Health endpoint returned: $HEALTH_CHECK"
fi

# Test status endpoint
STATUS_CHECK=$(curl -sSL -o /dev/null -w "%{http_code}" https://$DOMAIN/channel/status)
if [ "$STATUS_CHECK" = "200" ]; then
    print_status "Status endpoint: https://$DOMAIN/channel/status ✓"
else
    print_warning "Status endpoint returned: $STATUS_CHECK"
fi

# Test metrics endpoint
METRICS_CHECK=$(curl -sSL -o /dev/null -w "%{http_code}" https://$DOMAIN/channel/metrics)
if [ "$METRICS_CHECK" = "200" ]; then
    print_status "Metrics endpoint: https://$DOMAIN/channel/metrics ✓"
else
    print_warning "Metrics endpoint returned: $METRICS_CHECK"
fi

# Final summary
echo ""
echo "🎉 ========== SSL SETUP COMPLETE =========="
echo ""
print_status "HTTPS is now enabled on $DOMAIN"
echo ""
echo "📊 Available endpoints:"
echo "   • Dashboard: https://$DOMAIN"
echo "   • API Status: https://$DOMAIN/channel/status"
echo "   • Metrics: https://$DOMAIN/channel/metrics"
echo "   • Nodes: https://$DOMAIN/channel/nodes"
echo "   • API Docs: https://$DOMAIN/api/docs"
echo "   • WebSocket: wss://$DOMAIN/ws"
echo "   • Vizro Dashboard: https://$DOMAIN/vizro"
echo ""
echo "🔒 SSL Certificate Information:"
/usr/local/bin/check-ssl.sh
echo ""
echo "📝 Useful commands:"
echo "   • Check certificate: /usr/local/bin/check-ssl.sh"
echo "   • Renew certificate: sudo certbot renew"
echo "   • View nginx logs: tail -f /var/log/nginx/dlt.aurigraph.io.*.log"
echo "   • Reload nginx: sudo systemctl reload nginx"
echo ""
echo "✅ Your Aurigraph DLT platform is now secure with HTTPS!"
echo "==========================================="