// ================================================================================
// AUREX LAUNCHPAD™ CARBON MATURITY NAVIGATOR REPORT CENTER
// Sub-Application #13: Report Generation and Management Interface
// Module ID: LAU-MAT-013-FE-REPORTS - Report Center Component
// Created: August 7, 2025
// ================================================================================

import React, { useState, useEffect } from 'react';
import { 
  Assessment, 
  AssessmentReport, 
  ReportType, 
  ReportFormat,
  ReportConfiguration,
  BrandingConfig 
} from '../../types/carbonMaturityNavigator';
import carbonMaturityNavigatorApi from '../../services/carbonMaturityNavigatorApi';
import LoadingSpinner from '../LoadingSpinner';

interface ReportCenterProps {
  assessments: Assessment[];
  onBack: () => void;
}

const ReportCenter: React.FC<ReportCenterProps> = ({
  assessments,
  onBack
}) => {
  const [reports, setReports] = useState<AssessmentReport[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showGenerateForm, setShowGenerateForm] = useState(false);
  const [generatingReports, setGeneratingReports] = useState<Set<string>>(new Set());

  const [reportForm, setReportForm] = useState({
    assessment_id: '',
    report_type: ReportType.EXECUTIVE_SUMMARY,
    report_format: ReportFormat.PDF,
    config: {
      include_executive_summary: true,
      include_scoring_details: true,
      include_benchmarking: true,
      include_recommendations: true,
      include_evidence_summary: false,
      include_audit_trail: false,
      branding_config: {
        primary_color: '#3b82f6',
        secondary_color: '#10b981',
        font_family: 'Inter',
        cover_page_template: 'standard',
        footer_text: 'Generated by Aurex Carbon Maturity Navigator™'
      },
      custom_sections: []
    } as ReportConfiguration
  });

  useEffect(() => {
    loadReports();
  }, [assessments]);

  const loadReports = async () => {
    setIsLoading(true);
    setError(null);

    try {
      const allReports: AssessmentReport[] = [];
      
      for (const assessment of assessments) {
        try {
          const assessmentReports = await carbonMaturityNavigatorApi.getAssessmentReports(assessment.id);
          allReports.push(...assessmentReports);
        } catch (err) {
          console.warn(`Failed to load reports for assessment ${assessment.id}:`, err);
        }
      }

      setReports(allReports.sort((a, b) => 
        new Date(b.generated_date || '').getTime() - new Date(a.generated_date || '').getTime()
      ));
    } catch (err: any) {
      console.error('Failed to load reports:', err);
      setError(err.message || 'Failed to load reports');
    } finally {
      setIsLoading(false);
    }
  };

  const handleGenerateReport = async () => {
    if (!reportForm.assessment_id) {
      alert('Please select an assessment');
      return;
    }

    setGeneratingReports(prev => new Set(prev).add(reportForm.assessment_id));

    try {
      const report = await carbonMaturityNavigatorApi.generateReport(
        reportForm.assessment_id,
        reportForm.report_type,
        reportForm.report_format,
        reportForm.config
      );

      // Add to reports list
      setReports(prev => [report, ...prev]);
      setShowGenerateForm(false);

      // Reset form
      setReportForm(prev => ({
        ...prev,
        assessment_id: ''
      }));

    } catch (err: any) {
      console.error('Failed to generate report:', err);
      alert(`Failed to generate report: ${err.message}`);
    } finally {
      setGeneratingReports(prev => {
        const newSet = new Set(prev);
        newSet.delete(reportForm.assessment_id);
        return newSet;
      });
    }
  };

  const handleDownloadReport = async (report: AssessmentReport) => {
    try {
      const blob = await carbonMaturityNavigatorApi.downloadReport(report.id);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${report.report_type}_${report.id}.${report.report_format}`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (err: any) {
      console.error('Failed to download report:', err);
      alert(`Failed to download report: ${err.message}`);
    }
  };

  const getReportTypeLabel = (type: ReportType): string => {
    const labels = {
      [ReportType.EXECUTIVE_SUMMARY]: 'Executive Summary',
      [ReportType.DETAILED_ASSESSMENT]: 'Detailed Assessment',
      [ReportType.BENCHMARK_COMPARISON]: 'Benchmark Comparison',
      [ReportType.IMPROVEMENT_ROADMAP]: 'Improvement Roadmap',
      [ReportType.CERTIFICATION]: 'Certification Report',
      [ReportType.AUDIT_REPORT]: 'Audit Report'
    };
    return labels[type] || type;
  };

  const getStatusColor = (status: string) => {
    const colors = {
      pending: 'bg-yellow-100 text-yellow-800',
      generating: 'bg-blue-100 text-blue-800',
      completed: 'bg-green-100 text-green-800',
      failed: 'bg-red-100 text-red-800'
    };
    return colors[status] || 'bg-gray-100 text-gray-800';
  };

  const formatDate = (dateString?: string) => {
    if (!dateString) return 'N/A';
    return new Date(dateString).toLocaleString();
  };

  if (isLoading) {
    return (
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="flex items-center justify-center py-12">
          <LoadingSpinner />
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center justify-between">
          <div>
            <button
              onClick={onBack}
              className="inline-flex items-center text-blue-600 hover:text-blue-800 mb-4"
            >
              <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
              </svg>
              Back to Dashboard
            </button>
            
            <h1 className="text-3xl font-bold text-gray-900">Report Center</h1>
            <p className="text-gray-600">
              Generate and manage comprehensive assessment reports
            </p>
          </div>
          
          <button
            onClick={() => setShowGenerateForm(true)}
            className="bg-blue-600 text-white px-6 py-3 rounded-md hover:bg-blue-700 inline-flex items-center"
          >
            <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
            </svg>
            Generate Report
          </button>
        </div>
      </div>

      {error && (
        <div className="bg-red-50 border border-red-200 rounded-lg p-4 mb-6">
          <p className="text-red-800">{error}</p>
        </div>
      )}

      {/* Generate Report Modal */}
      {showGenerateForm && (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg shadow-xl max-w-2xl w-full max-h-screen overflow-y-auto">
            <div className="px-6 py-4 border-b border-gray-200">
              <div className="flex items-center justify-between">
                <h3 className="text-lg font-semibold text-gray-900">Generate New Report</h3>
                <button
                  onClick={() => setShowGenerateForm(false)}
                  className="text-gray-400 hover:text-gray-600"
                >
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            </div>
            
            <div className="p-6 space-y-6">
              {/* Assessment Selection */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Assessment *
                </label>
                <select
                  value={reportForm.assessment_id}
                  onChange={(e) => setReportForm(prev => ({ ...prev, assessment_id: e.target.value }))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  required
                >
                  <option value="">Select an assessment...</option>
                  {assessments.map((assessment) => (
                    <option key={assessment.id} value={assessment.id}>
                      {assessment.title} - {assessment.assessment_number}
                    </option>
                  ))}
                </select>
              </div>

              {/* Report Type */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Report Type *
                </label>
                <select
                  value={reportForm.report_type}
                  onChange={(e) => setReportForm(prev => ({ ...prev, report_type: e.target.value as ReportType }))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  {Object.values(ReportType).map((type) => (
                    <option key={type} value={type}>
                      {getReportTypeLabel(type)}
                    </option>
                  ))}
                </select>
              </div>

              {/* Format */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Format *
                </label>
                <select
                  value={reportForm.report_format}
                  onChange={(e) => setReportForm(prev => ({ ...prev, report_format: e.target.value as ReportFormat }))}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  {Object.values(ReportFormat).map((format) => (
                    <option key={format} value={format}>
                      {format.toUpperCase()}
                    </option>
                  ))}
                </select>
              </div>

              {/* Report Sections */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-3">
                  Include Sections
                </label>
                <div className="space-y-2">
                  {Object.entries({
                    include_executive_summary: 'Executive Summary',
                    include_scoring_details: 'Detailed Scoring Analysis',
                    include_benchmarking: 'Industry Benchmarking',
                    include_recommendations: 'Improvement Recommendations',
                    include_evidence_summary: 'Evidence Summary',
                    include_audit_trail: 'Audit Trail'
                  }).map(([key, label]) => (
                    <label key={key} className="flex items-center">
                      <input
                        type="checkbox"
                        checked={reportForm.config[key as keyof ReportConfiguration]}
                        onChange={(e) => setReportForm(prev => ({
                          ...prev,
                          config: {
                            ...prev.config,
                            [key]: e.target.checked
                          }
                        }))}
                        className="rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                      />
                      <span className="ml-2 text-sm text-gray-700">{label}</span>
                    </label>
                  ))}
                </div>
              </div>

              {/* Branding */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-3">
                  Branding
                </label>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-xs text-gray-600 mb-1">Primary Color</label>
                    <input
                      type="color"
                      value={reportForm.config.branding_config.primary_color}
                      onChange={(e) => setReportForm(prev => ({
                        ...prev,
                        config: {
                          ...prev.config,
                          branding_config: {
                            ...prev.config.branding_config,
                            primary_color: e.target.value
                          }
                        }
                      }))}
                      className="w-full h-10 rounded border border-gray-300"
                    />
                  </div>
                  
                  <div>
                    <label className="block text-xs text-gray-600 mb-1">Secondary Color</label>
                    <input
                      type="color"
                      value={reportForm.config.branding_config.secondary_color}
                      onChange={(e) => setReportForm(prev => ({
                        ...prev,
                        config: {
                          ...prev.config,
                          branding_config: {
                            ...prev.config.branding_config,
                            secondary_color: e.target.value
                          }
                        }
                      }))}
                      className="w-full h-10 rounded border border-gray-300"
                    />
                  </div>
                </div>
              </div>
            </div>
            
            <div className="px-6 py-4 border-t border-gray-200 flex justify-end space-x-3">
              <button
                onClick={() => setShowGenerateForm(false)}
                className="px-4 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50"
              >
                Cancel
              </button>
              
              <button
                onClick={handleGenerateReport}
                disabled={!reportForm.assessment_id}
                className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                Generate Report
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Reports List */}
      <div className="bg-white rounded-lg shadow-lg">
        <div className="px-6 py-4 border-b border-gray-200">
          <h3 className="text-lg font-semibold text-gray-900">Generated Reports</h3>
          <p className="text-sm text-gray-600 mt-1">
            {reports.length} report{reports.length !== 1 ? 's' : ''} available
          </p>
        </div>
        
        {reports.length === 0 ? (
          <div className="text-center py-12">
            <svg className="w-16 h-16 mx-auto mb-4 text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            <h3 className="text-lg font-medium text-gray-900 mb-2">No Reports Available</h3>
            <p className="text-gray-600 mb-6">Generate your first assessment report to get started.</p>
            <button
              onClick={() => setShowGenerateForm(true)}
              className="bg-blue-600 text-white px-6 py-2 rounded-md hover:bg-blue-700"
            >
              Generate Report
            </button>
          </div>
        ) : (
          <div className="divide-y divide-gray-200">
            {reports.map((report) => {
              const assessment = assessments.find(a => a.id === report.assessment_id);
              const isGenerating = generatingReports.has(report.assessment_id);
              
              return (
                <div key={report.id} className="px-6 py-4 hover:bg-gray-50">
                  <div className="flex items-center justify-between">
                    <div className="flex-1">
                      <div className="flex items-center space-x-3 mb-2">
                        <h4 className="text-lg font-medium text-gray-900">
                          {getReportTypeLabel(report.report_type)}
                        </h4>
                        
                        <span className={`inline-flex items-center px-2 py-1 rounded-full text-xs font-medium ${getStatusColor(report.generation_status)}`}>
                          {isGenerating ? (
                            <>
                              <svg className="w-3 h-3 mr-1 animate-spin" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                              </svg>
                              Generating...
                            </>
                          ) : (
                            report.generation_status.charAt(0).toUpperCase() + report.generation_status.slice(1)
                          )}
                        </span>
                        
                        <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-100 text-gray-800">
                          {report.report_format.toUpperCase()}
                        </span>
                      </div>
                      
                      <p className="text-sm text-gray-600 mb-1">
                        Assessment: {assessment?.title || 'Unknown'} ({assessment?.assessment_number || 'N/A'})
                      </p>
                      
                      <p className="text-xs text-gray-500">
                        Generated: {formatDate(report.generated_date)} • By: {report.generated_by}
                      </p>
                    </div>
                    
                    <div className="flex items-center space-x-3">
                      {report.generation_status === 'completed' && (
                        <>
                          <button
                            onClick={() => handleDownloadReport(report)}
                            className="inline-flex items-center px-3 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50"
                          >
                            <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                            </svg>
                            Download
                          </button>
                          
                          <button className="inline-flex items-center px-3 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50">
                            <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.367 2.684 3 3 0 00-5.367-2.684z" />
                            </svg>
                            Share
                          </button>
                        </>
                      )}
                      
                      <button className="text-gray-400 hover:text-red-600">
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                        </svg>
                      </button>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* Report Templates */}
      <div className="mt-8 bg-blue-50 rounded-lg p-6">
        <h3 className="text-lg font-semibold text-blue-900 mb-4">Available Report Types</h3>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {Object.values(ReportType).map((type) => (
            <div key={type} className="bg-white rounded-lg p-4 border border-blue-200">
              <h4 className="font-medium text-gray-900 mb-2">
                {getReportTypeLabel(type)}
              </h4>
              <p className="text-sm text-gray-600 mb-3">
                {type === ReportType.EXECUTIVE_SUMMARY && 'High-level overview for leadership and stakeholders'}
                {type === ReportType.DETAILED_ASSESSMENT && 'Comprehensive analysis with full scoring breakdown'}
                {type === ReportType.BENCHMARK_COMPARISON && 'Industry comparison and peer analysis'}
                {type === ReportType.IMPROVEMENT_ROADMAP && 'Strategic improvement plan and recommendations'}
                {type === ReportType.CERTIFICATION && 'Certification-ready compliance report'}
                {type === ReportType.AUDIT_REPORT && 'Audit trail and verification documentation'}
              </p>
              
              <button
                onClick={() => {
                  setReportForm(prev => ({ ...prev, report_type: type }));
                  setShowGenerateForm(true);
                }}
                className="text-blue-600 hover:text-blue-800 text-sm font-medium"
              >
                Generate →
              </button>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default ReportCenter;