#!/bin/bash

# GitHub Secrets Setup Script for Aurigraph DLT Deployment
# This script helps configure the required GitHub secrets for the deployment workflow

echo "================================================"
echo "GitHub Secrets Configuration for Aurigraph DLT"
echo "================================================"
echo ""
echo "Please configure the following secrets in your GitHub repository:"
echo "Go to: Settings > Secrets and variables > Actions"
echo ""
echo "Required Secrets:"
echo "-----------------"
echo ""
echo "1. SERVER_USERNAME"
echo "   Value: subbu"
echo "   Description: SSH username for the deployment server"
echo ""
echo "2. SERVER_HOST"
echo "   Value: dlt.aurigraph.io"
echo "   Description: Hostname or IP address of the deployment server"
echo ""
echo "3. SERVER_PORT"
echo "   Value: 2235"
echo "   Description: SSH port for the deployment server"
echo ""
echo "4. SERVER_SSH_PRIVATE_KEY"
echo "   Description: Private SSH key for authentication"
echo "   To generate if you don't have one:"
echo "   $ ssh-keygen -t rsa -b 4096 -C 'github-actions@aurigraph.io' -f ~/.ssh/github_deploy_key"
echo "   Then copy the private key content:"
echo "   $ cat ~/.ssh/github_deploy_key"
echo "   And add the public key to the server:"
echo "   $ ssh-copy-id -p 2235 -i ~/.ssh/github_deploy_key.pub subbu@dlt.aurigraph.io"
echo ""
echo "Optional Secrets (with defaults):"
echo "----------------------------------"
echo ""
echo "5. DB_PASSWORD"
echo "   Default: AurigraphSecure2025!"
echo "   Description: PostgreSQL database password"
echo ""
echo "6. REDIS_PASSWORD"
echo "   Default: AurigraphRedis2025!"
echo "   Description: Redis cache password"
echo ""
echo "================================================"
echo ""
echo "Using GitHub CLI? Run these commands:"
echo "--------------------------------------"
echo ""
echo "# First, login to GitHub CLI"
echo "gh auth login"
echo ""
echo "# Set the secrets (replace with actual values)"
echo "gh secret set SERVER_USERNAME --body 'subbu'"
echo "gh secret set SERVER_HOST --body 'dlt.aurigraph.io'"
echo "gh secret set SERVER_PORT --body '2235'"
echo "gh secret set SERVER_SSH_PRIVATE_KEY < ~/.ssh/github_deploy_key"
echo ""
echo "# Optional: Set custom passwords"
echo "gh secret set DB_PASSWORD --body 'YourSecurePassword'"
echo "gh secret set REDIS_PASSWORD --body 'YourRedisPassword'"
echo ""
echo "================================================"
echo ""
echo "Server Requirements:"
echo "--------------------"
echo "✓ Docker and Docker Compose installed"
echo "✓ SSL certificates at: /etc/letsencrypt/live/aurcrt/"
echo "✓ Web root directory: /var/www/html/"
echo "✓ Ports 80 and 443 open in firewall"
echo ""
echo "Deployment Triggers:"
echo "--------------------"
echo "• Push to 'main' branch"
echo "• Push to 'production' branch"
echo "• Manual trigger from Actions tab"
echo ""
echo "================================================"
